# test_flags.py

"""
--help or -h --> Used to get all the flags in the pytest...
-v --> Verbose (Detail View of Execution)...
-rA --> To get all the failed & passed status with detail explanation of it...
-k --> To execute the TC's with the key available in the method name...
"""
